#!/usr/bin/env bash

if [ $PWD != $DOTFILES ]; then
    echo "Not in the dotfiles repository root directory!"
    echo "[Exit with code 1]"
    exit 1
fi

branch=$(git rev-parse --abbrev-ref HEAD)
echo "On branch '$branch':"

function pull_from_master() {
    git add -A;
    git status
    read -p "Do you want to commit and push these changes? [Y/n]" -n 1 -r
    echo    
    if [[ $REPLY =~ ^[Yy]$ ]]
    then
        git commit -m "this commit was created automatically"
        git push origin $branch
        git checkout master
        git checkout $branch install-scripts nvim personal scripts tmux zsh .gitignore
        git add -A
        git commit -m "automatic update due to push in other branch"
        git push origin master
        git checkout $branch

    fi
}


if [ $branch = "master" ]; then
	echo "pull all to master"
    git pull origin master
elif [ $branch = "surfacebook" ]; then
	echo "merging only non setup specific stuff to master"
    pull_from_master
elif [ $branch = "surfacebook-dockin" ]; then
	echo "merging only non setup specific stuff to master"
    pull_from_master
else
	echo "Failed to match branch"
    exit 1
fi


